---
title: "Final"
author: "Andrew Maloney"
date: "5/1/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r} 
# Packages used for the Final Project

library(countrycode)
library(tidyverse)
library(readxl)
library(maps)
library(RColorBrewer)
library(viridis)
library(rworldmap)
library(maptools)
library(dplyr)
library(ggplot2)
library(plotly) 
library(gifski)
library(gganimate)

```


```{r}
#Datasets used for the Final Project

Current_USD <- read_excel('Military_Expenditure_Data.xlsx', sheet = 'Current USD') #Sipri Dataset

Share_of_GDP <- read_excel('Military_Expenditure_Data.xlsx', sheet = 'Share of GDP', skip = 5) #Sipri Dataset

Arms_Import <- read_excel('Arms_Imported.xlsx', sheet = "Data", skip = 3) #WorldBank Dataset obtained from Sipri

Military_Personal <- read_excel('Armed_Forces_Personel.xlsx', sheet = 'Data', skip = 3) #WorldBank Dataset obtained from Sipri

GlobalFirePower <- read_excel('GlobalFirePower.xlsx', sheet = 'GlobalFirePower')

```

```{r}
#Cleaning of Datasets 
#Gathering columns and mutating values to numeric
# Datasets messy formats were all similar

Current_USD <- Current_USD %>% gather(Year, Value, -Country, -Notes) %>% mutate(Value = as.numeric(Value), Year = as.numeric(Year)) %>% filter(!is.na(Value)) %>% mutate(Value = Value)

Share_of_GDP <- Share_of_GDP %>% gather(Year, Value, -Country, -Notes) %>% mutate(Value = as.numeric(Value), Year = as.numeric(Year)) %>% filter(!is.na(Value))

Arms_Import <- Arms_Import %>% gather(Year, Value, -`Country Name`, -`Country Code`) %>% mutate(Value = as.numeric(Value), Year = as.numeric(Year)) %>% rename(Country = `Country Name`, iso3c = `Country Code`) %>% filter(!is.na(Value))

Military_Personal <- Military_Personal %>% gather(Year, Value, -`Country Name`, -`Country Code`) %>% mutate(Value = as.numeric(Value), Year = as.numeric(Year)) %>% rename(Country = `Country Name`, iso3c = `Country Code`) %>% filter(!is.na(Value)) 

```

```{r}
#Adding missing countries and country codes 

Current_USD <- Current_USD %>% mutate(iso3c = countrycode(Country, "country.name", destination = "iso3c")) %>% mutate(iso3c = ifelse(Country == "Kosovo", "KOS", iso3c))

Current_USD[Current_USD$Country == "Central African Rep.", "iso3c"] <- "CAF"

Share_of_GDP <- Share_of_GDP %>% mutate(iso3c = countrycode(Country, "country.name", destination = "iso3c")) %>% mutate(iso3c = ifelse(Country == "Kosovo", "KOS", iso3c))

Share_of_GDP[Share_of_GDP$Country == "Central African Rep.", "iso3c"] <- "CAF" # Adding

```

```{r}
#We are using a large GeoSpatialDataframe to Plot Countires and their information
#Libraries we will use for this
#Loading Geo_spatial Data Frame created @ https://geojson-maps.ash.ms/
library(broom)
library(geojsonio)

world_map <-  geojsonio::geojson_read('custom.geo.json', what = 'sp')


world_map <- tidy(world_map, region = "sov_a3") # Changing from large spatial dataframe to regular data frame.

world_map <- world_map %>% mutate(iso3c = id)

#Adding ISO
#Manual searched for incorrect country codes and fixed them to match
world_map[world_map$id == "US1", "iso3c"] <- "USA"
world_map[world_map$id == "CH1", "iso3c"] <- "CHN"
world_map[world_map$id == "AU1", "iso3c"] <- "AUS"
world_map[world_map$id == "DN1", "iso3c"] <- "DNK"
world_map[world_map$id == "FI1", "iso3c"] <- "FIN"
world_map[world_map$id == "FR1", "iso3c"] <- "FRA"
world_map[world_map$id == "GB1", "iso3c"] <- "GBR"
world_map[world_map$id == "NL1", "iso3c"] <- "NLD"
world_map[world_map$id == "NZ1", "iso3c"] <- "NZL"

#Practice Plot
world_map %>% ggplot(aes(x = long, y = lat, group = group))+ geom_polygon()

```

```{r}
#Statistical Plots 
#We are going to do some exploratory Visualization 

#Comparing top Militaries Spending
Current_USD %>% group_by(Country, iso3c, Year, Value) %>% filter(Year >= 1992) %>% filter(Country %in% c("USA", "Russian Federation", "China, P.R.", "India", "France")) %>% ggplot(aes(x = Year, y = Value))+ geom_line(aes(color = Country)) + ggtitle("Military Expenditure Country USD")+ xlab("Years")+ ylab("Current Prices")+scale_x_continuous(breaks = c(1992:2017))+ scale_y_continuous(breaks = c(0e+00, 2e+05, 4e+05, 6e+05), labels = c("Hundreds of Millions", "200 Billion", "400 Billion", "600 Billion"))+ theme(axis.text.x = element_text(angle = 80, vjust = 1, hjust = 1))

Current_USD %>% group_by(Country, iso3c, Year, Value) %>% filter(Year >= 1992) %>% filter(Country %in% c("USA", "Russian Federation", "China, P.R.", "India", "France")) %>% ggplot(aes(x = Year, y = log2(Value)))+ geom_line(aes(color = Country)) + ggtitle("Military Expenditure Country USD")+ xlab("Years")+ ylab("Current Prices Log2")+scale_x_continuous(breaks = c(1992:2017))+ theme(axis.text.x = element_text(angle = 80, vjust = 1, hjust = 1))


#Comparing weak military Spending

Current_USD %>% group_by(Country, iso3c, Year, Value) %>% filter(Year >= 1992) %>% filter(Country %in% c("Ireland", "Sierra Leone", "Ghana", "Latvia", "Estonia")) %>% ggplot(aes(x = Year, y = Value))+ geom_line(aes(color = Country)) + ggtitle("Military Expenditure(Weak) Country USD")+ xlab("Year")+ ylab("Current Prices")+scale_x_continuous(breaks = c(1992:2017))+ theme(axis.text.x = element_text(angle = 80, vjust = 1, hjust = 1))+ scale_y_continuous(breaks = c(0, 500, 1000, 1500), labels = c("10s of Millions", "500 Million", "1 Billion", "1.5 Billion"))+ theme(axis.text.x = element_text(angle = 80, vjust = 1, hjust = 1))


Current_USD %>% group_by(Country, iso3c, Year, Value) %>% filter(Year >= 1992) %>% filter(Country %in% c("Ireland", "Sierra Leone", "Ghana", "Latvia", "Estonia")) %>% ggplot(aes(x = Year, y = log2(Value)))+ geom_line(aes(color = Country)) + ggtitle("Military Expenditure(Weak) Country USD")+ xlab("Year")+ ylab("Current Prices Log2")+scale_x_continuous(breaks = c(1992:2017))+ theme(axis.text.x = element_text(angle = 80, vjust = 1, hjust = 1))


#------------------------------------------------------------------------#

#Comparing top Militaries Spending based on GDP
Share_of_GDP %>% group_by(Country, iso3c, Year, Value) %>% filter(Year >= 1992) %>% filter(Country %in% c("USA", "Russian Federation", "China, P.R.", "India", "France")) %>% ggplot(aes(x = Year, y = Value))+ geom_line(aes(color = Country))+ ggtitle("Military Expenditure as % of GDP")+ xlab("Year")+ ylab("Military Expenditure")+ scale_y_continuous(labels = scales::percent)+scale_x_continuous(breaks = c(1992:2017))+ theme(axis.text.x = element_text(angle = 80, vjust = 1, hjust = 1))

#Comparing weak Militaries Spending based on GDP
Share_of_GDP %>% group_by(Country, iso3c, Year, Value) %>% filter(Year >= 1992) %>% filter(Country %in% c("Ireland", "Sierra Leone", "Ghana", "Latvia", "Estonia")) %>% ggplot(aes(x = Year, y = Value))+ geom_line(aes(color = Country))+ ggtitle("Military Expenditure as % of GDP")+ xlab("Year")+ ylab("Military Expenditure")+ scale_y_continuous(labels = scales::percent)+scale_x_continuous(breaks = c(1992:2017))+ theme(axis.text.x = element_text(angle = 80, vjust = 1, hjust = 1))

#------------------------------------------------------------------------#

#Comparing Top Countries Military Personal

Military_Personal %>% subset(Country %in% c("United States", "Russian Federation", "China", "India", "France")) %>% filter(Year >= 1992) %>% ggplot(aes(x = Year, y = Value))+ geom_line(aes(color = Country))+scale_x_continuous(breaks = c(1992:2016))+ theme(axis.text.x = element_text(angle = 80, vjust = 1, hjust = 1))+ggtitle("Military Personal % of Labor Force")+ xlab("Years")+ ylab("Military Personal")

#Comparing Weak Countries Military Personal
Military_Personal %>% subset(Country %in% c("Ireland", "Sierra Leone", "Ghana", "Latvia", "Estonia")) %>% filter(Year >= 1992) %>% ggplot(aes(x = Year, y = Value))+ geom_line(aes(color = Country))+scale_x_continuous(breaks = c(1992:2016))+ theme(axis.text.x = element_text(angle = 80, vjust = 1, hjust = 1))+ggtitle("Military Expenditure as % Labor Force")+ xlab("Years")+ ylab("Military Personal")  
    
#------------------------------------------------------------------------#

#Comparing top Militaries Arm imports
Arms_Import %>% subset(Country %in% c("United States", "Russian Federation", "China", "India", "France")) %>% filter(Year >= 1992) %>% ggplot(aes(x = Year, y = Value))+ geom_line(aes(color = Country))+ ggtitle("Military Arms Import")+ xlab("Year")+ ylab("Military Arms")+scale_x_continuous(breaks = c(1992:2016))+ scale_y_continuous(breaks = c(2.000e+06, 1.029e+09, 2.500e+09, 5.322e+09), labels = c("2 Million", "1 Billion", "2.5 Billion", "5 Billion"))+ theme(axis.text.x = element_text(angle = 80, vjust = 1, hjust = 1)) #Number of Arm imports for each powerful Country



#Comparing Weak Militaries Arm imports
Arms_Import %>% subset(Country %in% c("Ireland", "Sierra Leone", "Ghana", "Latvia", "Estonia")) %>% filter(Year >= 1992) %>% ggplot(aes(x = Year, y = Value))+ geom_line(aes(color = Country))+ ggtitle("Military Arms Import")+ xlab("Year")+ ylab("Military Arms")+scale_x_continuous(breaks = c(1992:2016))+ scale_y_continuous(breaks = c(2.000e+06, 15.000e+06, 38.000e+06, 76.000e+06), labels = c("2 Million", "15 Million", "38 Million", "76 Million"))+ theme(axis.text.x = element_text(angle = 80, vjust = 1, hjust = 1)) #Number of Arm imports for each powerful Country




#------------------------------------------------------------------------#

#Countries Military Arsenals for Year 2017
#Statistic

GlobalFirePower_X<- GlobalFirePower %>% select(Country, ISO3, `Total Aircraft Strength`, `Total Helicopter Strength`, `Combat Tanks`, 19, 20, 23)

GlobalFirePower_X %>% filter(Country %in% c("United States", "Russia", "China", "India", "France")) %>% summary()

GlobalFirePower_X %>% filter(Country %in% c("Ireland", "Sierra Leone", "Ghana", "Latvia", "Estonia")) %>% summary()

```


```{r}
#Mexico Information

Current_USD %>% group_by(Country, iso3c, Year, Value) %>% filter(Country == "Mexico") %>% filter(Year >= 1970) %>% ggplot(aes(x = Year, y = Value))+ geom_point()+ geom_line()+ ggtitle("Mexico's Military Expenditure")+ xlab("Year")+ ylab("Current Prices")+ scale_y_continuous(breaks = c(0, 2500, 5000, 7500), labels = c("Hundreds of Millions", "2.5 Billion", "5 Billion", "7.5 Billion"))



#-----------------------------------------------------------------------------------------------------#
Share_of_GDP %>% group_by(Country, iso3c, Year, Value) %>% filter(Country == "Mexico") %>% filter(Year >= 1970) %>% ggplot(aes(x = Year, y = Value * 100))+ geom_point()+ geom_line()+ ggtitle("Mexico's Military Expenditure as % of GDP")+ xlab("Year")+ ylab("Percent of GDP")+scale_y_continuous(breaks = c(.400, .500, .600, .700), labels = c("4%", "5%", "6%", "7%"))


#-----------------------------------------------------------------------------------------------------#
Military_Personal %>% filter(Country == "Mexico") %>% filter(Year >= 1970) %>% ggplot(aes(x = Year, y = Value))+ geom_point()+ geom_line()+
  ggtitle("Mexico's Military Personal as % of Labor Force")+ xlab("Year")+ ylab("Military Personal")+ scale_y_continuous(breaks = c(.45, .50, .55, .60, .65), labels = c(".45%", ".50%", ".55%", ".60%", ".65%"))# Really good graph show mexicos military increase as a percent of labor force



#-----------------------------------------------------------------------------------------------------#
Arms_Import %>% filter(Country == "Mexico") %>% filter(Year >= 1970) %>% ggplot(aes(x = Year, y = Value))+ geom_point()+ geom_line()+
   ggtitle("Mexico's Military Arms Import")+ xlab("Year")+ ylab("Military Arms")+ scale_y_continuous(breaks = c(0e+00, 1e+08, 2e+08, 3e+08, 4e+08, 5e+08), labels = c("6 Million", "100 Million", "200 Million", "300 Million", "400 Million", "500 Million"))+ theme(axis.text.x = element_text(angle = 80, vjust = 1, hjust = 1))



#-----------------------------------------------------------------------------------------------------#
GlobalFirePower_X<- GlobalFirePower %>% select(Country, ISO3, `Total Aircraft Strength`, `Total Helicopter Strength`, `Combat Tanks`, 19, 20, 23)

GlobalFirePower_X %>% filter(Country == "Mexico")


```



```{r}
#Current USD
data_for_map <- Current_USD %>% group_by(Country) %>% filter(Year == max(Year))

world_map_join <- world_map %>% left_join(data_for_map, by = "iso3c")

Flat_Map <- world_map_join %>% ggplot(aes(x = long, y = lat, group = group, fill = log(Value)))+
  geom_polygon() + scale_fill_viridis(option = "inferno", direction = -1)

Flat_Map

#______________________________________________________________________________#

data_for_map_gdp <- Share_of_GDP %>% group_by(Country) %>% filter(Year == max(Year))

world_map_join_gdp <- world_map %>% left_join(data_for_map_gdp, by = "iso3c")

Flat_Map_gdp <- world_map_join_gdp %>% ggplot(aes(x = long, y = lat, group = group, fill = Value))+
  geom_polygon() + scale_fill_viridis(option = "inferno", direction = -1)

Flat_Map_gdp

```

```{r}
#Current USD
Animation_Prep <- Current_USD %>% group_by(Country)
Animation_Prep_2 <- Share_of_GDP %>% group_by(Country)

Animation_Map <- world_map %>% left_join(Animation_Prep, by = "iso3c")
Animation_Map_2 <- world_map %>% left_join(Animation_Prep_2, by = "iso3c")
#Animation_Map <- na.omit(Animation_Map)

Animation <- ggplot() + geom_polygon(data = world_map, aes(x = long, y = lat, group = group))+
  geom_polygon(data = Animation_Map, aes(x = long, y = lat, group = group, fill = log(Value)))+ 
  scale_fill_distiller(palette = "BuGn", direction = 1 )+ theme_dark()+
  transition_time(Year, range = c(2000, 2017)) + ease_aes('linear') 


AnimationX <- ggplot() + geom_polygon(data = world_map, aes(x = long, y = lat, group = group))+
  geom_polygon(data = Animation_Map_2, aes(x = long, y = lat, group = group, fill = log(Value)))+ 
  scale_fill_distiller(palette = "BuGn", direction = 1 )+ theme_dark()+
  transition_time(Year, range = c(1970, 2017)) + ease_aes('linear')


```

```{r}

#animate(Animation) 
#animate(Animation_2)


```



