---
title: "Map Creation(Rough Sketch 2)"
author: "Andrew Maloney"
date: "4/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(countrycode)
library(tidyverse)
library(readxl)
library(maps)
library(RColorBrewer)
library(viridis)
library(rworldmap)
library(maptools)
library(dplyr)
library(ggplot2)
library(plotly) 

#  Reading Libraries 
```

```{r}
Expenditure_USD <- read_excel('Military_Expenditure_Data.xlsx', sheet = 'Current USD')  
# Reading Excel Sheet
# This sheet has also been cleaned up in excel.  There were multiple imbedded pictures and links, so I removed them before I used R.  


Prep_data <- Expenditure_USD %>% gather(Year, Value, -Country, -Notes) %>% mutate(Value = as.numeric(Value), Year = as.numeric(Year)) %>% filter(!is.na(Value)) #gathering columns and mutating values to numeric

str(Prep_data)

```
```{r}
Prep_data_2 <- Prep_data %>% mutate(iso3c = countrycode(Country, "country.name", destination = "iso3c")) %>% mutate(iso3c = ifelse(Country == "Kosovo", "KOS", iso3c))


Prep_data_2[Prep_data_2$Country == "Central African Rep.", "iso3c"] <- "CAF" # Adding ISO 

#table(Prep_data_2$iso3c)
#table(world_map_join$iso3c)
```

```{r}
library(broom)
library(geojsonio)
world_map <-  geojsonio::geojson_read('custom.geo.json', what = 'sp') # Loading Geo_spatial Data Frame created @ https://geojson-maps.ash.ms/


world_map_prep <- tidy(world_map, region = "sov_a3") # Changing from large spatial dataframe to regular data frame.
world_map_prep <- world_map_prep %>% mutate(iso3c = id)

world_map_prep[world_map_prep$id == "US1", "iso3c"] <- "USA"
world_map_prep[world_map_prep$id == "CH1", "iso3c"] <- "CHN"
world_map_prep[world_map_prep$id == "AU1", "iso3c"] <- "AUS"
world_map_prep[world_map_prep$id == "DN1", "iso3c"] <- "DNK"
world_map_prep[world_map_prep$id == "FI1", "iso3c"] <- "FIN"
world_map_prep[world_map_prep$id == "FR1", "iso3c"] <- "FRA"
world_map_prep[world_map_prep$id == "GB1", "iso3c"] <- "GBR"
world_map_prep[world_map_prep$id == "NL1", "iso3c"] <- "NLD"
world_map_prep[world_map_prep$id == "NZ1", "iso3c"] <- "NZL"
#Adding ISO

world_map_prep %>% ggplot(aes(x = long, y = lat, group = group))+ geom_polygon() # Making sure plot worked


```

```{r}
data_for_map <- Prep_data_2 %>% group_by(Country) %>% filter(Year == max(Year))

summary(data_for_map$Year)

world_map_join <- world_map_prep %>% left_join(data_for_map, by = "iso3c")



Flat_Map <- world_map_join %>% ggplot(aes(x = long, y = lat, group = group, fill = log(Value)))+
  geom_polygon(colour = "green") + scale_fill_viridis(option = "inferno", direction = -1)

Flat_Map

ggplotly(Flat_Map)

```