---
title: "Proposal_FreshCode"
author: "Andrew Maloney"
date: "4/3/2019"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(readxl) 
library(dplyr) 
library(forcats)
library(ggplot2)
library(tidyr)
library(stringr)
library(reshape2)
library(broom)
library(mapproj)
library(sp)
library(maptools)

```

```{r}
Expenditure_USD <- read_excel('Military_Expenditure_Data.xlsx', sheet = 'Current USD')
head(Expenditure_USD)
str(Expenditure_USD)
```

```{r}
Expenditure_USD_V1 <- Expenditure_USD %>% gather(key = Country_Year, value = Numerical_Expenditure, 3:71)
```

```{r}
Expenditure_USD_V1[Expenditure_USD_V1 == ". ."] <- NA
Expenditure_USD_V1[Expenditure_USD_V1 == "xxx"] <- NA
Expenditure_USD_V1[Expenditure_USD_V1 == "NA"] <- NA 
Expenditure_USD_V1
```

```{r}
Expenditure_USD_V2 <- Expenditure_USD_V1 %>% select(-Notes) %>% mutate(Country_Year = as.numeric(Country_Year), Numerical_Expenditure = as.numeric(Numerical_Expenditure))
Expenditure_USD_V2
```

```{r}
summary(Expenditure_USD_V2$Numerical_Expenditure)
table(Expenditure_USD_V2$Country)
```

```{r}
classifications <- c('North Africa', 'Africa', 'Oceania', 'Europe', 'Central Europe', 'Eastern Europe', 'Western Europe', 'Middle East', 'Sub-Saharan', 'Americas', 'Central America and the Caribbean', '', 'North America', 'Asia & Oceania', 'Central Asia', 'East Asia', 'South Asia', 'South-East Asia') #These are more like "regions" and contain no data at all.  I am removing them.
Expenditure_USD_V3 <- Expenditure_USD_V2 %>% filter(!Country %in% classifications) %>% filter(!is.na(Country))
table(Expenditure_USD_V3$Country)
sum(table(unique(Expenditure_USD_V3$Country)))
Expenditure_USD_V3
```


```{r}
Expenditure_USD_V4 <- Expenditure_USD_V3 %>% mutate(Numerical_Expenditure = as.integer(Numerical_Expenditure))
#Expenditures are in USD millions of Dollars


```


```{r}
world_map <-  geojsonio::geojson_read('custom.geo.json', what = 'sp')
#print(world_map)
world_map2 <- fortify(world_map)

str(world_map2)

ggplot(world_map2, mapping = aes(x = long, y = lat, group = group)) +
  geom_polygon() +
  coord_cartesian(xlim = c(-180, 180), ylim = c(-84, 84))
```
